
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DimplomApp.DataBase
{

using System;
    using System.Collections.Generic;
    
public partial class Clients
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Clients()
    {

        this.Services_client = new HashSet<Services_client>();

    }


    public int ID_client { get; set; }

    public string First_name { get; set; }

    public string Last_name { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Mail { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Services_client> Services_client { get; set; }

}

}
