
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DimplomApp.DataBase
{

using System;
    using System.Collections.Generic;
    
public partial class Documents
{

    public int ID_document { get; set; }

    public Nullable<DateTime> Date { get; set; }

    public Nullable<int> NotaryID { get; set; }

    public Nullable<int> PriceID { get; set; }

    public Nullable<int> Services { get; set; }

    public decimal? ServiceSum { get; set; }




    public virtual Notaries Notaries { get; set; }

    public virtual Price_list Price_list { get; set; }

    public virtual Services_client Services_client { get; set; }

}

}
