
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DimplomApp.DataBase
{

using System;
    using System.Collections.Generic;

    public partial class Finance
    {
        public int ID_finance { get; set; }
        public Nullable<int> Type_of_OperationID { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<int> ExpensesID { get; set; }
        public DateTime? Date { get; set; }
        public DateTime Date_expenses { get; set; }
        public DateTime Date_payments { get; set; }
        public string OperationType { get; set; }

        public virtual Expenses Expenses { get; set; }
        public virtual Payments Payments { get; set; }
        public virtual Type_of_operation Type_of_operation { get; set; }
    }

}
